version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: commerce-erp-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root@1234}
      MYSQL_DATABASE: ${DATABASE_NAME:-commerce_erp}
      MYSQL_USER: ${DATABASE_USERNAME:-commerce}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-commerce@1234}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
      # Docker 네트워크에서의 접근을 위한 설정
      MYSQL_ROOT_HOST: '%'
    ports:
      - '${DATABASE_PORT:-3306}:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./docker/mariadb/conf/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - commerce-erp-network
    # MariaDB 설정 파일 추가 (선택사항)
    command: >
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: commerce_erp
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      DATABASE_HOST: mariadb
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-commerce}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-commerce@1234}
      DATABASE_NAME: ${DATABASE_NAME:-commerce_erp}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-your_32_character_encryption_key}
      FILE_UPLOAD_MAX_SIZE: ${FILE_UPLOAD_MAX_SIZE:-10485760}
      ALLOWED_FILE_EXTENSIONS: ${ALLOWED_FILE_EXTENSIONS:-csv,json}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      # 개발 환경에서 seeder 실행 활성화
      ENABLE_SEEDER: ${ENABLE_SEEDER:-true}
      # 관리자 계정 설정
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      ADMIN_COMPANY_ID: ${ADMIN_COMPANY_ID:-admin_company}
      ADMIN_COMPANY_NAME: ${ADMIN_COMPANY_NAME:-Admin Company}
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    networks:
      - commerce-erp-network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
          '||',
          'exit',
          '1',
        ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local

networks:
  commerce-erp-network:
    driver: bridge
